version: '3.8'

services:
  
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python bot.py
    volumes:
      - .:/app
    depends_on:
      - web
    restart: always



volumes:
  pg_data:
    driver: local
